[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.0.0"

# Handle SPA routing and refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  [redirects.headers]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Redirect www to non-www
[[redirects]]
  from = "https://www.code-playgr0und.netlify.app/*"
  to = "https://code-playgr0und.netlify.app/:splat"
  status = 301
  force = true

# Handle 404s
[[redirects]]
  from = "/404"
  to = "/"
  status = 302

[headers]
  # Headers for all pages
  for = "/*"
    [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()
