[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.0.0"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/playground/*"
  to = "/"
  status = 200
  force = true
